### ISSUE TITLE
Sub-issue of email links | 'Interested status'

### ISSUE THREAD

**Issue by iteles** [FAC-GM/app#383]
Linked to #301 (Status update links in emails).

Functionality when button is clicked:
+ [ ] Takes candidate to a 'thank you, your option has been recorded' page
  + [ ] **Open question:** Does this need to be on the Global {M} website to allow them to then click around (we would need TOAD for this)? Or just a page on the app? Note they would then see the URL of the app in their address bar and that might be odd
+ [ ] No longer allows candidate to be mass emailed in the app **for one month**
+ [ ] Add 'Interested' tag to the candidate's individual profile _(not in the search results)_
+ [ ] Add a link from somewhere on the homepage that allows everyone to see the profiles that have indicated they are 'interested' (the display for this will be like the search results display)
