### ISSUE TITLE
Sub-issue of email links | 'Contact me in 2 months' status

### ISSUE THREAD

**Issue by iteles** [FAC-GM/app#384]
Linked to #301 (Status update links in emails). The longer term view of this is to allow candidates to determine _when_ they want to be contacted again.

Functionality when button is clicked:
+ [ ] Takes candidate to a 'thank you, your option has been recorded' page
  + [ ] **Open question:** Does this need to be on the Global {M} website to allow them to then click around (we would need TOAD for this)? Or just a page on the app? Note they would then see the URL of the app in their address bar and that might be odd
+ [ ] No longer allows candidate to be mass emailed in the app **for two months**
+ [ ] Add 'Contact again on x date' information to the candidate's individual profile _(not in the search results)_

_Currently_ there are no plans to display people who have this status as a group of people (i.e. you can't click on a tag that takes you to a list of these people).
